#!/bin/sh

PREREQ=""

prereqs()
{
     echo "$PREREQ"
}


case $1 in
    prereqs)
        prereqs
        exit 0
    ;;
esac

set -eu

exit_if_root_ok()
{
    if [ -b "${ROOT}" ]; then
        echo "ROOT OK"
        exit 0
    fi
}

exit_if_root_ok

if [ -x /sbin/lvm ]; then
    i=0
    while [ $i -lt 10 ]; do
        echo "$i: fixing root ${ROOT}"
        # /sbin/lvm vgscan
        /sbin/lvm vgchange -a y --sysinit
        i=$(($i + 1))

        exit_if_root_ok
        sleep 0.5
    done
fi

