#!/bin/sh

PREREQ=""

prereqs()
{
     echo "$PREREQ"
}

mountfail()
{
    if [ -x /sbin/lvm ]; then
        echo "puavo-lvm-fix: Fixing..."
        set -x
        /sbin/lvm vgscan
        /sbin/lvm vgchange -a y --sysinit
        exit 0
    fi
}

case $1 in
    prereqs)
        prereqs
        exit 0
    ;;
    mountfail)
        mountfail
        # did nothing. Exit with 1
        exit 1
    ;;
esac

. /scripts/functions

echo "Registering puavo-lvm-fix as mountroot_fail_hook"
add_mountroot_fail_hook "puavo-lvm-fix"

exit 0

